const CANVAS_PADDING = 20;
const PILLER_GAP = 100;
const TABLE_WIDTH = 200;
const TABLE_GAP = 20;


const TABLE_CORNER_R = 10;
const TABLE_BORDER_WIDTH = 3;
const TABLE_BORDER_COLOR = "#9bacab";
const TABLE_BORDER_COLOR_SELECTED = "#FF6201";
const TABLE_HEADER_BGCOLOR = "#2a2d57";
const COLUMN_TEXT_OFFSET_HEADER_X = 12;
const COLUMN_TEXT_OFFSET_HEADER_Y = 25;
const TABLE_HEADER_FONTSIZE = 20;
const TABLE_HEADER_TEXTCOLOR = "#e8e8e8";
const TABLE_COLUMN_ODD_BGCOLOR = "#d1ccab";
const TABLE_COLUMN_EVEN_BGCOLOR = "#dddbcf";
const COLUMN_TEXT_OFFSET_COLUMN_X = 18;
const COLUMN_TEXT_OFFSET_COLUMN_Y = 21;
const TABLE_COLUMN_FONTSIZE = 18;
const TABLE_COLUMN_TEXTCOLOR = "#333333"
const TABLE_HEADER_HEIGHT = 35;
const TABLE_COLUMN_HEIGHT = 30;

// ---- コネクション（テーブル間） ----
// 線の色
const TBL_CONNECTION_COLOR = "#cc9231";
// 線の幅
const TBL_CONNECTION_WIDTH = 3;
// 末端の埋め込み深さ
const TBL_CONNECTION_ENBEDDED = 0;
// 末端の円の半径
const TBL_CONNECTION_END_DOT_R = 5;

// ---- コネクション（列間） ----
// 線の色
const COL_CONNECTION_COLOR = "#edc277";
// 線の幅
const COL_CONNECTION_WIDTH = 2;
// 末端の色
const COL_CONNECTION_END_COLOR = "#ccab73";
// 末端の円の半径
const COL_CONNECTION_END_DOT_R = 4;

const SVG_MIN_WIDTH = 800;
const SVG_MIN_HEIGHT = 500;


export {
    CANVAS_PADDING,
    PILLER_GAP,
    TABLE_WIDTH,
    TABLE_GAP,

    TABLE_CORNER_R,
    TABLE_BORDER_WIDTH,
    TABLE_BORDER_COLOR,
    TABLE_BORDER_COLOR_SELECTED,
    TABLE_HEADER_BGCOLOR,
    COLUMN_TEXT_OFFSET_HEADER_X,
    COLUMN_TEXT_OFFSET_HEADER_Y,
    TABLE_HEADER_FONTSIZE,
    TABLE_HEADER_TEXTCOLOR,
    TABLE_COLUMN_ODD_BGCOLOR,
    TABLE_COLUMN_EVEN_BGCOLOR,
    COLUMN_TEXT_OFFSET_COLUMN_X,
    COLUMN_TEXT_OFFSET_COLUMN_Y,
    TABLE_COLUMN_FONTSIZE,
    TABLE_COLUMN_TEXTCOLOR,
    TABLE_HEADER_HEIGHT,
    TABLE_COLUMN_HEIGHT,

    // コネクション（テーブル間）
    TBL_CONNECTION_COLOR,
    TBL_CONNECTION_WIDTH,
    TBL_CONNECTION_ENBEDDED,
    TBL_CONNECTION_END_DOT_R,

    // コネクション（列間）
    COL_CONNECTION_COLOR,
    COL_CONNECTION_END_COLOR,
    COL_CONNECTION_WIDTH,
    COL_CONNECTION_END_DOT_R,

    SVG_MIN_WIDTH,
    SVG_MIN_HEIGHT,
};

